import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const repo = path.resolve(fileURLToPath(import.meta.url), "../../..");
const HEADER = /GENERATED by translate\/[a-z]+\.mjs from (\S+?)\. /;

function walk(dir, found = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".git") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, found);
    else if (entry.isFile()) found.push(full);
  }
  return found;
}

function headerSource(file) {
  let text;
  try {
    text = fs.readFileSync(file, "utf8");
  } catch {
    return null;
  }
  const head = text.split("\n").slice(0, 80).join("\n");
  const m = HEADER.exec(head);
  return m ? m[1] : null;
}

test("every GENERATED header names a repo-relative source that exists", () => {
  const bad = [];
  let checked = 0;
  for (const top of ["claude", "codex", "cursor"]) {
    for (const file of walk(path.join(repo, top))) {
      const src = headerSource(file);
      if (src === null) continue;
      checked++;
      const rel = path.relative(repo, file);
      const ok = !path.isAbsolute(src) && fs.existsSync(path.join(repo, src));
      if (!ok) bad.push(`${rel} says "from ${src}"`);
    }
  }
  assert.ok(checked > 0, "no generated files found; the scan proved nothing");
  assert.equal(
    bad.length,
    0,
    `${bad.length} of ${checked} generated files name a source that is not a repo path:\n${bad.slice(0, 10).join("\n")}`,
  );
});

test("node translate/all.mjs --check exits 0 on the committed tree", () => {
  const r = spawnSync(process.execPath, [path.join(repo, "translate", "all.mjs"), "--check"], {
    cwd: repo,
    encoding: "utf8",
  });
  assert.equal(r.status, 0, `status=${r.status}\n${r.stdout}${r.stderr}`);
});
