#!/usr/bin/env bash
# Shard: slow
# Covers: hook:protected-path-guard
# Verifies the generated-file guard (spec B-7, B-8): a Write or Edit to an
# existing file whose first lines carry a `GENERATED by translate/<b>.mjs from
# <src>.` header is denied with a message naming <src> and the regenerate
# command; files without the header, new files, and a header past the first
# few lines are left alone. The Codex adapter must reach the same denial.
set -uo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/../../enforce/harness-root.sh"
HOOK="$CLAUDE_HARNESS_ROOT/hooks/protected-path-guard.sh"
export CLAUDE_ROLE_POLICY_FILE="$CLAUDE_HARNESS_ROOT/enforce/role-policy.json"
REPO_TOP=$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)
ADAPTER="$REPO_TOP/codex/hooks/codex-hook-adapter.sh"

# Strip GIT_* so a hook-spawned run cannot leak GIT_DIR into the fixture repo.
for v in $(env | grep -o '^GIT_[A-Z_]*' || true); do unset "$v"; done

WORK=$(cd "$(mktemp -d)" && pwd -P)
trap 'rm -rf "$WORK" "$WORK-failed"' EXIT
git -C "$WORK" init -q
mkdir -p "$WORK/claude/agents" "$WORK/claude/hooks" "$WORK/claude/enforce" "$WORK/codex/agents"

CLAUDE_HDR='<!-- GENERATED by translate/claude.mjs from rules/GLOBAL.md. Do not edit; change the source and run: node translate/all.mjs --write -->'
CODEX_HDR='<!-- GENERATED by translate/codex.mjs from rules/GLOBAL.md. Do not edit; change the source and run: node translate/all.mjs --write -->'
AGENT_HDR='<!-- GENERATED by translate/claude.mjs from rules/agents/x.md. Do not edit; change the source and run: node translate/all.mjs --write -->'
TOML_HDR='# <!-- GENERATED by translate/codex.mjs from rules/agents/x.md. Do not edit; change the source and run: node translate/all.mjs --write -->'

printf '%s\n\nbody\n' "$CLAUDE_HDR" > "$WORK/claude/CLAUDE.md"
printf -- '---\nname: x\n---\n%s\n\nbody\n' "$AGENT_HDR" > "$WORK/claude/agents/x.md"
# Real agents carry more frontmatter (pr-reviewer.md has its header on line 8).
printf -- '---\nname: x\ndescription: d\ntools: Read\ndisallowedTools: Write\nmodel: sonnet\n---\n%s\n\nbody\n' "$AGENT_HDR" > "$WORK/claude/agents/long.md"
printf '%s\n\nbody\n' "$CODEX_HDR" > "$WORK/codex/AGENTS.md"
printf '%s\nname = "x"\n' "$TOML_HDR" > "$WORK/codex/agents/x.toml"
printf '#!/usr/bin/env bash\necho hi\n' > "$WORK/claude/hooks/x.sh"
printf '#!/usr/bin/env bash\necho hi\n' > "$WORK/claude/enforce/y.sh"
{ for i in $(seq 1 99); do echo "line $i"; done; echo '<!-- GENERATED by translate/claude.mjs from rules/GLOBAL.md. late mention -->'; } > "$WORK/late.md"

write() { jq -nc --arg f "$1" --arg d "$WORK" \
  '{tool_name:"Write",cwd:$d,tool_input:{file_path:$f,content:"new content\n"}}'; }
edit() { jq -nc --arg f "$1" --arg o "$2" --arg n "$3" --arg d "$WORK" \
  '{tool_name:"Edit",cwd:$d,tool_input:{file_path:$f,old_string:$o,new_string:$n}}'; }
decision() { local out; out=$("$HOOK" 2>/dev/null); if [ -z "$out" ]; then echo allow; else printf '%s' "$out" | jq -r '.hookSpecificOutput.permissionDecision'; fi; }

fail=0
# expect runs inside a pipeline subshell, so record failures in a file.
FAILFILE="$WORK-failed"
mark_fail() { echo x >> "$FAILFILE"; }
expect() {
  local want="$1" label="$2" got
  got=$(decision)
  if [ "$got" = "$want" ]; then echo "PASS: $label"; else echo "FAIL: $label: expected $want, got $got"; mark_fail; fi
}
expect_reason() {
  local pattern="$1" label="$2" out
  out=$("$HOOK" 2>/dev/null)
  if printf '%s' "$out" | jq -r '.hookSpecificOutput.permissionDecisionReason // ""' | grep -qF -- "$pattern"; then
    echo "PASS: $label"
  else echo "FAIL: $label: reason did not contain '$pattern'"; mark_fail; fi
}

# --- generated files are denied ----------------------------------------------
write "$WORK/claude/CLAUDE.md" | expect deny "Write to a claude.mjs-generated file (header on line 1)"
write "$WORK/claude/CLAUDE.md" | expect_reason 'rules/GLOBAL.md' "deny reason names the source"
write "$WORK/claude/CLAUDE.md" | expect_reason 'node translate/all.mjs --write' "deny reason names the regenerate command"
edit "$WORK/claude/agents/x.md" 'body' 'other' | expect deny "Edit to an agent whose header sits on line 4 after frontmatter"
edit "$WORK/claude/agents/long.md" 'body' 'other' | expect deny "Edit to an agent whose header sits on line 8 after longer frontmatter"
edit "$WORK/claude/agents/x.md" 'body' 'other' | expect_reason 'rules/agents/x.md' "agent deny reason names its source"
write "$WORK/codex/AGENTS.md" | expect deny "Write to a codex.mjs-generated file"
write "$WORK/codex/agents/x.toml" | expect deny "Write to a codex TOML file with a '# ' prefixed header"
edit "$WORK/codex/agents/x.toml" 'name = "x"' 'name = "y"' | expect deny "Edit to a codex TOML file"

# --- everything else is untouched (B-8) --------------------------------------
write "$WORK/claude/agents/new.md" | expect allow "Write to a path that does not exist yet"
write "$WORK/claude/hooks/x.sh" | expect allow "Write to claude/hooks/x.sh with no header"
edit "$WORK/claude/hooks/x.sh" 'echo hi' 'echo ho' | expect allow "Edit to claude/hooks/x.sh with no header"
write "$WORK/claude/enforce/y.sh" | expect allow "Write to claude/enforce/y.sh with no header"
edit "$WORK/claude/enforce/y.sh" 'echo hi' 'echo ho' | expect allow "Edit to claude/enforce/y.sh with no header"
write "$WORK/late.md" | expect allow "Write to a file mentioning GENERATED by only on line 100"
jq -nc '{tool_name:"Read",tool_input:{file_path:"'"$WORK"'/claude/CLAUDE.md"}}' | expect allow "Read of a generated file is never gated"

# --- the Codex adapter reaches the same denial -------------------------------
run_adapter() {
  printf '%s' "$1" | env -u CLAUDE_HOOK_RUNTIME \
    CLAUDE_HOME="$REPO_TOP/claude" \
    CLAUDE_SETTINGS_FILE="$REPO_TOP/claude/settings.json" \
    CLAUDE_ROLE_POLICY_FILE="$REPO_TOP/claude/enforce/role-policy.json" \
    CLAUDE_CODEX_STATE_DIR="$WORK/state" \
    CLAUDE_CODEX_WRITE_TARGET_HOOKS="" \
    bash "$ADAPTER" protected-path-guard
}
patch_payload() { jq -n --arg p "$1" --arg cwd "$WORK" \
  '{hook_event_name:"PreToolUse", tool_name:"apply_patch", tool_input:{command:$p}, cwd:$cwd}'; }
update_patch() { printf '*** Begin Patch\n*** Update File: %s\n@@\n-body\n+other\n*** End Patch\n' "$1"; }

OUT=$(run_adapter "$(patch_payload "$(update_patch "claude/CLAUDE.md")")" 2>/dev/null)
if [ "$(printf '%s' "$OUT" | jq -r '.hookSpecificOutput.permissionDecision // "none"')" = deny ]; then
  echo "PASS: adapter denies an apply_patch Update File on a generated file"
else echo "FAIL: adapter did not deny an apply_patch Update File on a generated file: $OUT"; fail=1; fi
if printf '%s' "$OUT" | grep -qF 'rules/GLOBAL.md'; then echo "PASS: adapter denial names the source"
else echo "FAIL: adapter denial did not name rules/GLOBAL.md"; fail=1; fi

OUT=$(run_adapter "$(patch_payload "$(update_patch "claude/hooks/x.sh")")" 2>/dev/null)
if [ -z "$OUT" ]; then echo "PASS: adapter allows an apply_patch on a headerless hook"
else echo "FAIL: adapter blocked a headerless hook: $OUT"; fail=1; fi

# --- git restore of a generated file is allowed; other writes stay denied ----
printf '{}\n' > "$WORK/.enforce.json"
bash_cmd() { jq -nc --arg c "$1" --arg d "$WORK" '{tool_name:"Bash",cwd:$d,tool_input:{command:$c}}'; }
for c in \
  'git checkout -- codex/AGENTS.md' \
  'git checkout origin/main -- claude/CLAUDE.md' \
  'git checkout --theirs claude/CLAUDE.md' \
  'git restore codex/AGENTS.md' \
  'git restore --source=HEAD --staged --worktree claude/CLAUDE.md'; do
  bash_cmd "$c" | expect allow "git restore of a generated file is not denied: $c"
done
bash_cmd 'git checkout -- claude/CLAUDE.md && echo x > claude/CLAUDE.md' | expect deny "restore combined with a direct write is denied"
bash_cmd 'git checkout -- claude/CLAUDE.md && echo x > claude/CLAUDE.md' | expect_reason 'rules/GLOBAL.md' "combined-command denial names the source"
for c in 'git rm claude/CLAUDE.md' 'rm claude/CLAUDE.md' 'cp /tmp/x claude/CLAUDE.md'; do
  bash_cmd "$c" | expect deny "write verb on a generated file stays denied: $c"
done
bash_cmd 'git checkout -- .enforce.json' | expect deny "git checkout of a gate input (.enforce.json) stays denied"
bash_cmd 'git restore .enforce.json' | expect deny "git restore of a gate input (.enforce.json) stays denied"

[ -s "$FAILFILE" ] && fail=1
[ "$fail" -eq 0 ] && echo "generated-file-guard.test.sh PASS"
exit "$fail"
