#!/usr/bin/env node
// claude.mjs: renders claude/'s prose files (CLAUDE.md, CLAUDE-<STACK>.md,
// CLOUD-DEPLOYMENT.md, PROTOCOL.md, agents/, skills/, prompts/) from the
// tool-neutral sources under rules/ (spec docs/specs/2026-10-04-neutral-rules-source.md).
// Everything else under claude/ (hooks, enforce, settings.json, global-memory,
// README.md, SETUP.md) is hand-authored and never touched: orphan sweeping is
// limited to claude/agents, claude/skills, claude/prompts, and root-level
// claude/*.md files that carry this builder's GENERATED header.
import fs from "node:fs";
import path from "node:path";
import { loadJsonFile, SourceError } from "./parse-sources.mjs";
import { renderGeneratedHeaderFor, runExporterCli } from "./exporter-core.mjs";
import { loadRuleSources } from "./rule-sources.mjs";

const BUILDER = "translate/claude.mjs";
const TARGET_SUBDIR = "claude";
const SWEPT_SUBDIRS = ["agents", "skills", "prompts"];
const USAGE = "usage: node translate/claude.mjs --write|--check [--root <repo-dir>]";
const HEADER_PREFIX = `<!-- GENERATED by ${BUILDER} from `;

function header(source) {
  return renderGeneratedHeaderFor(BUILDER, source);
}

// withHeader(text, source): the text with the header line inserted. A file
// that opens with a frontmatter block (stack rules carry `paths:` for Claude
// Code's path-scoped loading through claude/rules/) keeps it on line 1, so
// the header goes right after the block; otherwise the header is line 1.
function withHeader(text, source) {
  const frontmatter = /^---\r?\n[\s\S]*?\r?\n---\r?\n/.exec(text);
  if (frontmatter) {
    return `${frontmatter[0]}${header(source)}\n${text.slice(frontmatter[0].length)}`;
  }
  return `${header(source)}\n${text}`;
}

// withFrontmatterHeader(entry): frontmatter first (Claude Code reads it from
// line 1), then the header line, then the filtered body.
function withFrontmatterHeader(entry) {
  return `---\n${entry.rawFrontmatter}\n---\n${header(entry.source)}\n${entry.body}`;
}

function loadSources(rootDir) {
  const portMap = loadJsonFile(path.join(rootDir, "translate/claude-port-map.json"));
  if (!Array.isArray(portMap.hand_authored)) {
    throw new SourceError("translate/claude-port-map.json", "hand_authored must be an array");
  }
  return { portMap, rules: loadRuleSources(rootDir, "claude") };
}

// Planned files, paths relative to claude/.
function renderPlannedTree(sources) {
  const { rules } = sources;
  const planned = [
    { path: "CLAUDE.md", content: withHeader(rules.global.text, rules.global.source) },
    { path: "CLOUD-DEPLOYMENT.md", content: withHeader(rules.cloudDeployment.text, rules.cloudDeployment.source) },
    { path: "PROTOCOL.md", content: withHeader(rules.protocol.text, rules.protocol.source) },
    ...rules.stacks.map((stack) => ({ path: stack.legacyName, content: withHeader(stack.text, stack.source) })),
    ...rules.agents.map((agent) => ({ path: `agents/${path.basename(agent.file)}`, content: withFrontmatterHeader(agent) })),
    ...rules.prompts.map((prompt) => ({ path: `prompts/${prompt.name}`, content: withHeader(prompt.text, prompt.source) })),
  ];
  for (const skill of rules.skills) {
    planned.push({ path: `skills/${skill.dirName}/SKILL.md`, content: withFrontmatterHeader(skill) });
    for (const file of skill.supportFiles) {
      planned.push({ path: `skills/${skill.dirName}/${file.rel}`, content: file.content, mode: file.mode });
    }
  }
  return planned;
}

function listFilesRecursive(dir) {
  if (!fs.existsSync(dir)) return [];
  const found = [];
  const walk = (sub) => {
    for (const entry of fs.readdirSync(path.join(dir, sub), { withFileTypes: true })) {
      const rel = sub ? `${sub}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(rel);
      else found.push(rel);
    }
  };
  walk("");
  return found.sort();
}

function firstLine(file) {
  try { return fs.readFileSync(file, "utf8").split("\n", 1)[0]; } catch { return ""; }
}

// findOrphans(rootDir, planned, handAuthored): claude/-relative paths this
// builder owns but no longer plans: anything under the swept subdirectories,
// plus root-level *.md files that start with this builder's header.
function findOrphans(rootDir, planned, handAuthored) {
  const claudeDir = path.join(rootDir, TARGET_SUBDIR);
  const plannedPaths = new Set(planned.map((file) => file.path));
  const owned = [];
  for (const sub of SWEPT_SUBDIRS) {
    for (const rel of listFilesRecursive(path.join(claudeDir, sub))) owned.push(`${sub}/${rel}`);
  }
  if (fs.existsSync(claudeDir)) {
    for (const name of fs.readdirSync(claudeDir).sort()) {
      if (name.endsWith(".md") && firstLine(path.join(claudeDir, name)).startsWith(HEADER_PREFIX)) owned.push(name);
    }
  }
  return owned.filter((rel) => !plannedPaths.has(rel) && !handAuthored.includes(rel));
}

function removeEmptyDirs(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) removeEmptyDirs(path.join(dir, entry.name));
  }
  if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
}

function writePlannedTree(rootDir, planned, sources) {
  const claudeDir = path.join(rootDir, TARGET_SUBDIR);
  for (const file of planned) {
    const fullPath = path.join(claudeDir, file.path);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, file.content);
    if (file.mode !== undefined) fs.chmodSync(fullPath, file.mode);
  }
  const orphans = findOrphans(rootDir, planned, sources.portMap.hand_authored);
  for (const orphan of orphans) fs.unlinkSync(path.join(claudeDir, orphan));
  for (const sub of SWEPT_SUBDIRS) {
    const dir = path.join(claudeDir, sub);
    if (fs.existsSync(dir)) for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) removeEmptyDirs(path.join(dir, entry.name));
    }
  }
  const removedClause = orphans.length > 0 ? `, removed ${orphans.length} orphans` : "";
  console.log(`wrote ${planned.length} files${removedClause}`);
}

function checkPlannedTree(rootDir, planned, sources) {
  const claudeDir = path.join(rootDir, TARGET_SUBDIR);
  const lines = [];
  for (const file of planned) {
    let onDisk = null;
    try { onDisk = fs.readFileSync(path.join(claudeDir, file.path)); } catch { onDisk = null; }
    if (onDisk === null || !onDisk.equals(Buffer.from(file.content))) lines.push(`stale: ${file.path}`);
  }
  for (const orphan of findOrphans(rootDir, planned, sources.portMap.hand_authored)) lines.push(`orphaned: ${orphan}`);
  return { lines, hasFailure: lines.length > 0 };
}

runExporterCli(process.argv.slice(2), {
  builderName: "claude.mjs",
  usage: USAGE,
  loadSources,
  renderPlannedTree,
  writePlannedTree,
  checkPlannedTree,
});
