#!/usr/bin/env node
// exporter-core.mjs: target-agnostic machinery shared by every translate/*
// exporter (codex.mjs and cursor.mjs both reuse it): planned-tree writing
// and staleness checking, orphan detection, the GENERATED header line, the
// port manifest, the shared CLI entry-point harness (argument parsing,
// source-listing helpers, the load/render/write-or-check epilogue), and the
// glob-suffix agent-list matcher both exporters filter agents/skills
// through. Every function is parameterized by target subdir and/or builder
// path, so no codex- or cursor-specific knowledge lives here; target-
// specific checks (codex's hook-registration classification, for instance)
// stay in the caller and are layered on top of this module's results.
import path from "node:path";
import fs from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

// MANIFEST_PATH: the manifest's own target-relative path. Exported so a
// derived-content renderer that must list the manifest's path in its own
// output before the manifest itself has been built (render-cursor-
// gitignore.mjs's allowlist, which names every expected cursor/ path
// including the manifest) can reference the same constant instead of
// duplicating the literal string.
export const MANIFEST_PATH = ".claude-port.json";

// SourceError(file, why): the one error every translator input-loading and
// planned-tree-building step throws, naming the offending claude/ (or
// translate/) file so a caller can print a helpful message and exit 2.
// Lives here rather than in parse-sources.mjs (which used to define it)
// because this module's own claimPlannedPath below needs to throw it too,
// and parse-sources.mjs already imports from exporter-core.mjs; defining it
// here and having parse-sources.mjs import-then-re-export it keeps every
// existing `import { SourceError } from "./parse-sources.mjs"` call site
// valid without a circular import the other direction would create.
export class SourceError extends Error {
  constructor(file, why) { super(`${file}: ${why}`); this.file = file; }
}

// renderGeneratedHeaderFor(builderPath, source): the one GENERATED-header
// line every rendered target file carries, naming the translator script
// (builderPath) that produced it and the claude/ source it came from.
export function renderGeneratedHeaderFor(builderPath, source) {
  return `<!-- GENERATED by ${builderPath} from ${source}. Do not edit; change the source and run: node ${builderPath} --write -->`;
}

// --- Shared CLI harness (review I-3a): this section, plus runExporterCli
// below, used to be duplicated byte-for-byte in codex.mjs and cursor.mjs,
// apart from the usage string. One implementation, parameterized where the
// two exporters genuinely differ. ---

// parseCliMode(argv) -> { mode, rootDir } or { error: detail }: exactly one
// of --write or --check, an optional --root <dir> (default: two directories
// up from this shared module, which sits in translate/ beside every
// exporter), and no unknown or positional token. Never throws and never
// half-parses: a caller that sees .error has a diagnostic naming the
// offending token (PR #8 review: the generic usage line left the author
// guessing which argument was refused); runExporterCli below prefixes the
// exporter's own name and usage line before printing it.
export function parseCliMode(argv) {
  const known = new Set(["--write", "--check", "--root"]);
  const rootIndex = argv.indexOf("--root");
  // Every token is accounted for, not just the `--`-prefixed ones. Filtering
  // to `--` tokens meant a bare positional or a single-dash flag was silently
  // discarded and rootDir fell back to this script's own repository, so
  // `--check /some/other/tree` reported on the wrong tree and `--write` pruned
  // orphans and emptied directories in the wrong one (2026-09-17 audit P2-1).
  const rootValueIndex = rootIndex === -1 ? -1 : rootIndex + 1;
  const unexpected = argv.find((token, index) =>
    index !== rootValueIndex && !known.has(token));
  if (unexpected !== undefined) {
    return { error: `unrecognized argument "${unexpected}"; the repository directory goes after --root and there are no positional arguments` };
  }
  const modes = argv.filter((f) => f === "--write" || f === "--check");
  if (modes.length === 0) return { error: "no mode given; pass exactly one of --write or --check" };
  if (modes.length > 1) return { error: `${modes.join(" and ")} cannot both be given; pass exactly one of --write or --check` };
  if (rootIndex === -1) {
    return { mode: modes[0].slice(2), rootDir: path.resolve(fileURLToPath(import.meta.url), "../..") };
  }
  // A bare --root (no following value, or the next token is itself a flag)
  // is a usage error, not a crash: without this guard rootDir is undefined
  // and every later path.join(undefined, ...) throws a TypeError.
  const rootValue = argv[rootIndex + 1];
  if (rootValue === undefined) return { error: "--root was given with no repository directory after it" };
  if (rootValue.startsWith("--")) return { error: `--root was followed by the flag "${rootValue}" rather than a repository directory` };
  return { mode: modes[0].slice(2), rootDir: rootValue };
}

// listFilesWithExtension(dir, extension) -> sorted full paths: every entry
// directly under dir whose name ends with extension (".md", ".toml", ...),
// or [] when dir does not exist. Shared by both exporters' claude/agents/
// loaders.
export function listFilesWithExtension(dir, extension) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((name) => name.endsWith(extension)).sort().map((name) => path.join(dir, name));
}

// listSkillDirs(dir) -> sorted full paths to each skill directory under dir,
// or [] when dir does not exist. Shared by both exporters' claude/skills/
// loaders; the directory (not its SKILL.md) is the unit because a skill may
// bundle support files (scripts, reference material) beside its SKILL.md.
export function listSkillDirs(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(dir, entry.name))
    .sort();
}

// makeSkillSourceLoader(loadTextFileFn, splitFrontmatterFn) -> skillDir =>
// { file, frontmatter, rawFrontmatter, body, supportFiles }: loads a skill
// directory as its SKILL.md markdown source plus supportFiles, every other
// file under the directory as { rel, content, mode }, rel forward-slash
// separated relative to the skill directory, content a Buffer (a script is
// copied byte for byte, never decoded), mode the source's permission bits so
// an executable stays executable in the port. Factory-shaped for the same
// circularity reason as makeMarkdownSourceLoader above.
export function makeSkillSourceLoader(loadTextFileFn, splitFrontmatterFn) {
  const loadMarkdown = makeMarkdownSourceLoader(loadTextFileFn, splitFrontmatterFn);
  return (skillDir) => {
    const source = loadMarkdown(path.join(skillDir, "SKILL.md"));
    const supportFiles = listFilesRecursive(skillDir)
      .filter((rel) => rel !== "SKILL.md")
      .map((rel) => {
        const fullPath = path.join(skillDir, rel);
        return {
          rel: rel.split(path.sep).join("/"),
          content: fs.readFileSync(fullPath),
          mode: fs.statSync(fullPath).mode & 0o777,
        };
      });
    return { ...source, supportFiles };
  };
}

// renderSkillSupportFileFor(skill, file) -> { path, content, mode }: one
// file bundled beside a skill's SKILL.md (file.rel is its path relative to
// the skill directory, forward-slash separated), copied without alteration;
// a script cannot carry an HTML-comment GENERATED header, and the skill text
// references it by the same relative path in every port.
export function renderSkillSupportFileFor(skill, file) {
  const { name } = skill.frontmatter;
  return { path: `skills/${name}/${file.rel}`, content: file.content, mode: file.mode };
}

// makeMarkdownSourceLoader(loadTextFileFn, splitFrontmatterFn) -> file =>
// { file, frontmatter, rawFrontmatter, body }: both exporters load
// claude/agents/*.md and claude/skills/*/SKILL.md sources the identical
// way, reading the file and splitting its frontmatter. Takes loadTextFile
// and splitFrontmatter as parameters instead of importing them from
// parse-sources.mjs directly: parse-sources.mjs already imports SourceError
// and renderGeneratedHeaderFor from this module, so importing back the
// other way would be circular. Each caller builds its own loader once,
// closing over its own already-imported loadTextFile/splitFrontmatter.
export function makeMarkdownSourceLoader(loadTextFileFn, splitFrontmatterFn) {
  return (file) => ({ file, ...splitFrontmatterFn(loadTextFileFn(file), file) });
}

// runExporterCli(argv, hooks) -> never returns (always calls process.exit):
// the entry-point epilogue every translate/* exporter runs. Parses
// --write|--check|--root via parseCliMode above, printing hooks.usage and
// exiting 2 on any usage violation; loads sources and renders the planned
// tree inside a try/catch that turns any SourceError into the same exit-2
// path, naming the offending file; then either writes the planned tree and
// exits 0, or prints the check's lines and exits by hasFailure.
// hooks.loadSources(rootDir), hooks.renderPlannedTree(sources),
// hooks.writePlannedTree(rootDir, planned, sources), and
// hooks.checkPlannedTree(rootDir, planned, sources) are the four
// target-specific functions this sequences; hooks.usage is the exporter's
// own usage string, since this shared function cannot know which script
// name to print.
export function runExporterCli(argv, hooks) {
  const cli = parseCliMode(argv);
  if (cli.error) {
    console.error(`${hooks.builderName}: ${cli.error}\n${hooks.usage}`);
    process.exit(2);
  }
  let sources;
  let planned;
  try {
    sources = hooks.loadSources(cli.rootDir);
    planned = hooks.renderPlannedTree(sources);
  } catch (err) {
    if (!(err instanceof SourceError)) throw err;
    console.error(err.message);
    process.exit(2);
  }
  if (cli.mode === "write") {
    hooks.writePlannedTree(cli.rootDir, planned, sources);
    process.exit(0);
  }
  const { lines, hasFailure } = hooks.checkPlannedTree(cli.rootDir, planned, sources);
  for (const line of lines) console.log(line);
  process.exit(hasFailure ? 1 : 0);
}

// listFilesRecursive(dir) -> sorted paths relative to dir, forward-slash
// free (path.join keeps the platform separator, matched by callers that
// also build their planned paths with path.join): every regular file under
// dir, walked depth-first, dir itself omitted from each path.
function listFilesRecursive(dir) {
  if (!fs.existsSync(dir)) return [];
  const found = [];
  const walk = (subDir) => {
    for (const entry of fs.readdirSync(path.join(dir, subDir), { withFileTypes: true })) {
      const relPath = subDir ? path.join(subDir, entry.name) : entry.name;
      if (entry.isDirectory()) walk(relPath);
      else found.push(relPath);
    }
  };
  walk("");
  return found.sort();
}

// isRuntimeIgnoredPath(relPath, runtimeIgnoredList): true when the port map
// classifies this path runtime-only-ignored, either exactly or by directory
// prefix (an entry ending "/" covers everything under it). Runtime state a
// tool drops into the target tree survives the orphan sweep only when the
// map declares it; an undeclared stray is still an orphan (PR #13 review:
// the gitignore's blanket survive-anything promise was false, and the B-9
// class existed in the manifest without ever reaching the sweep).
function isRuntimeIgnoredPath(relPath, runtimeIgnoredList) {
  return runtimeIgnoredList.some((entry) =>
    entry.endsWith("/") ? relPath.startsWith(entry) : relPath === entry);
}

// findOrphanFiles(rootDir, targetSubdir, planned, handAuthoredList,
// runtimeIgnoredList) -> sorted target-relative paths: every file on disk
// under <rootDir>/<targetSubdir>/ that the planned tree did not plan,
// handAuthoredList does not name, and runtimeIgnoredList does not cover.
// Generated output whose claude/ source was deleted (an agent or skill file
// removed) leaves exactly this kind of file behind; the exporter owns
// generated content wholesale, so an orphan is always a defect, never
// intentional.
export function findOrphanFiles(rootDir, targetSubdir, planned, handAuthoredList, runtimeIgnoredList = []) {
  const plannedPaths = new Set(planned.map((file) => file.path));
  const handAuthoredPaths = new Set(handAuthoredList);
  return listFilesRecursive(path.join(rootDir, targetSubdir))
    .filter((relPath) => !plannedPaths.has(relPath) && !handAuthoredPaths.has(relPath)
      && !isRuntimeIgnoredPath(relPath, runtimeIgnoredList));
}

// removeEmptyDirectories(dir): deletes every directory under dir that holds
// no files, deepest first, leaving dir itself in place. Unlinking an orphan
// is only half of removing it: deleting a skill on the claude/ side orphans
// <target>/skills/<name>/SKILL.md, and the emptied directory it leaves behind
// is invisible to git (which stores no empty directories) and to --check
// (which compares files), so it would survive every later run unnoticed.
function removeEmptyDirectories(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) removeEmptyDirectories(path.join(dir, entry.name));
  }
  if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
}

// writePlannedTree(rootDir, targetSubdir, planned, handAuthoredList): writes
// every planned file under <rootDir>/<targetSubdir>/. Renders the full tree
// before writing the first file (the caller's job), so a render failure
// never leaves a partial write on disk; this function itself still writes
// all-in-memory-then-write, one mkdir -p per file's directory. Afterward it
// deletes every orphan (R-306/single-owner: the exporter owns generated
// content wholesale, so a stale leftover from a deleted claude/ source is
// never left for a human to notice by hand), skipping anything named in
// handAuthoredList so a human-edited file is never swept up as an orphan,
// and removes any directories the deletions emptied.
export function writePlannedTree(rootDir, targetSubdir, planned, handAuthoredList, runtimeIgnoredList = []) {
  for (const file of planned) {
    const fullPath = path.join(rootDir, targetSubdir, file.path);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, file.content);
    // A support file carries its source mode so a bundled script stays
    // executable; --check compares content only, so a mode-only drift is
    // repaired by the next --write rather than reported.
    if (file.mode !== undefined) fs.chmodSync(fullPath, file.mode);
  }
  const orphans = findOrphanFiles(rootDir, targetSubdir, planned, handAuthoredList, runtimeIgnoredList);
  for (const orphan of orphans) fs.unlinkSync(path.join(rootDir, targetSubdir, orphan));
  for (const entry of fs.readdirSync(path.join(rootDir, targetSubdir), { withFileTypes: true })) {
    if (entry.isDirectory()) removeEmptyDirectories(path.join(rootDir, targetSubdir, entry.name));
  }
  const removedClause = orphans.length > 0 ? `, removed ${orphans.length} orphans` : "";
  console.log(`wrote ${planned.length} files${removedClause}`);
}

// checkPlannedTree(rootDir, targetSubdir, planned, handAuthoredList) -> {
// lines, hasFailure }: compares the rendered tree against disk, reading
// only, never writing. `lines` carries every stale/missing-hand-authored/
// orphaned message; `hasFailure` is true when any of them fired.
// Target-specific checks (codex's hook-registration classification, for
// instance) are not this function's job: the caller appends its own lines
// and folds its own hasFailure in on top of this result.
export function checkPlannedTree(rootDir, targetSubdir, planned, handAuthoredList, runtimeIgnoredList = []) {
  const lines = [];
  let hasFailure = false;
  for (const file of planned) {
    const fullPath = path.join(rootDir, targetSubdir, file.path);
    let onDisk = null;
    try { onDisk = fs.readFileSync(fullPath); } catch { onDisk = null; }
    if (onDisk === null || !onDisk.equals(Buffer.from(file.content))) {
      lines.push(`stale: ${file.path}`);
      hasFailure = true;
    }
  }
  for (const entry of handAuthoredList) {
    if (!fs.existsSync(path.join(rootDir, targetSubdir, entry))) {
      lines.push(`missing hand-authored file: ${entry}`);
      hasFailure = true;
    }
  }
  for (const orphan of findOrphanFiles(rootDir, targetSubdir, planned, handAuthoredList, runtimeIgnoredList)) {
    lines.push(`orphaned: ${orphan}`);
    hasFailure = true;
  }
  return { lines, hasFailure };
}

// renderSkillCopyFor(builderPath, skill) -> { path: "skills/<name>/
// SKILL.md", content }: a claude/skills/<name>/SKILL.md source rendered
// verbatim to a target's skills/<name>/SKILL.md, except for the GENERATED
// header inserted immediately after the frontmatter's closing "---" line.
// Parameterized by builderPath (translate/codex.mjs, translate/cursor.mjs,
// ...) since the assembly (frontmatter, header, body) and the insertion
// point are identical for every target; only the header's own builder
// attribution differs. render-codex-skills.mjs and render-cursor-skills.mjs
// both wrap this instead of each re-implementing the same
// frontmatter-then-header-then-body assembly (R-308: reuse before
// duplicating).
export function renderSkillCopyFor(builderPath, skill) {
  const { name } = skill.frontmatter;
  const content =
    `---\n${skill.rawFrontmatter}\n---\n${renderGeneratedHeaderFor(builderPath, `skills/${name}/SKILL.md`)}\n${skill.body}`;
  return { path: `skills/${name}/SKILL.md`, content };
}

// matchesAgentSkillList(name, patterns): true when name exactly matches one
// of patterns, or starts with a pattern's prefix when that pattern ends in
// "*" (a glob-suffix match, not a full glob: only a trailing "*" is
// special). Both exporters filter claude/agents/*.md sources through this
// with the identical semantics (codex's agents_to_skills list, cursor's
// agents_to_subagents list), so it lives in the target-agnostic core rather
// than in either target-specific renderer (review I-2: this used to live in
// render-codex-agents.mjs, and render-cursor-agents.mjs imported it sideways
// from that codex-specific module, an unpredictable dependency edge a
// future change to codex's renderer could silently break).
export function matchesAgentSkillList(name, patterns) {
  return patterns.some((p) => (p.endsWith("*") ? name.startsWith(p.slice(0, -1)) : name === p));
}

// claimPlannedPath(seenPaths, sourceFile, plannedFile) -> plannedFile:
// registers plannedFile.path in seenPaths and returns plannedFile
// unchanged, so a caller can push the result straight onto its planned
// array (planned.push(claimPlannedPath(...))); throws SourceError naming
// sourceFile when the path is already in seenPaths. Every renderPlannedTree
// in this repo (codex.mjs, cursor.mjs) calls this once per file whose
// target path is derived from claude/ source content rather than fixed by
// the exporter's own rule-class layout, so two sources racing to own one
// target path (a duplicate agent frontmatter name, an agent-derived skill
// colliding with a same-named skill source) fail fast naming the second
// source, instead of writePlannedTree silently overwriting whichever wrote
// last (review round 1). One Set spans the caller's whole planned tree, not
// one Set per file type: a path collision is exactly as real a defect
// regardless of which two renderers produced the colliding paths.
export function claimPlannedPath(seenPaths, sourceFile, plannedFile) {
  if (seenPaths.has(plannedFile.path)) {
    throw new SourceError(sourceFile, `renders to ${plannedFile.path}, which another source already claimed`);
  }
  seenPaths.add(plannedFile.path);
  return plannedFile;
}

// sha256Hex(content): the manifest's digest format for one generated file's
// content, "sha256:<hex>".
function sha256Hex(content) {
  return `sha256:${createHash("sha256").update(content).digest("hex")}`;
}

// sortedByKey(obj): a shallow copy of obj with keys sorted lexicographically,
// so manifest output is deterministic regardless of render or classification
// order.
function sortedByKey(obj) {
  const sorted = {};
  for (const key of Object.keys(obj).sort()) sorted[key] = obj[key];
  return sorted;
}

// requireNoGeneratedHandAuthoredCollision(plannedFiles, classifications):
// throws when a hand_authored port-map entry names a path a renderer also
// plans to generate (review M-2). Reproduced by adding a hand_authored
// entry for an already-generated path (PORT-STATUS.md, say): the manifest
// simultaneously hashed the file as generated content and listed it as
// hand-authored, findOrphanFiles exempted it from orphan detection, and
// --write kept overwriting it on every run while the manifest told a
// reader it was human-owned, all while --check stayed green throughout.
// The check needs the original planned-file list, not classifications
// alone: each caller's own buildManifestClassifications-equivalent step
// already lets the hand-authored class silently overwrite a path's
// "generated" entry before this function ever sees it, so by the time
// classifications arrives here the collision has already been erased from
// that map and only plannedFiles still remembers the path was generated
// too.
function requireNoGeneratedHandAuthoredCollision(plannedFiles, classifications) {
  const plannedPaths = new Set(plannedFiles.map((file) => file.path));
  for (const [filePath, cls] of Object.entries(classifications)) {
    if (cls.startsWith("hand-authored") && plannedPaths.has(filePath)) {
      throw new SourceError(filePath, "port map names this path hand_authored, but a renderer also plans to generate it");
    }
  }
}

// buildManifest(builderPath, plannedFiles, classifications) -> { path:
// ".claude-port.json", content }: one hash per planned file, keyed by its
// target-relative path (the manifest cannot hash itself, so it is never in
// plannedFiles when this runs). classifications maps every planned and
// hand-authored path to one of the six B-9 classes (generated | importable |
// hand-authored-local | hand-authored-mapped | runtime-only-ignored |
// unsupported); the manifest carries that verbatim as a per-path "classes"
// map, and additionally derives the flat "hand_authored" array (every path
// classified hand-authored-local or hand-authored-mapped) for compatibility
// with the original codex manifest shape, which callers and the fixture
// still read. hand_authored is copied from classifications verbatim, order
// preserved: JS object key order is insertion order for string keys, and
// callers build classifications with hand-authored paths inserted in the
// port map's own declared order, so this reproduces the original
// port-map-driven hand_authored contract exactly. Never sort this array; a
// human diffing the manifest by eye reads it in the port map's order.
// hashBuilderFiles() -> { "translate/<name>.mjs": "sha256:<hex>" }: every
// module of the generator, keyed by repo-relative path and sorted. The
// enforcement surface's hash manifest (claude/enforce/hook-hashes.txt)
// cannot reach translate/ (sync.sh copies claude/ only), so the port
// manifest hashes the translator itself: an edit to the generator that was
// never blessed by a --write fails --check in CI and at pre-push. Resolved
// from this module's own location rather than the caller's --root, so the
// hashes describe the translator that actually ran.
function hashBuilderFiles() {
  const builderDir = path.dirname(fileURLToPath(import.meta.url));
  const names = fs.readdirSync(builderDir).filter((name) => name.endsWith(".mjs")).sort();
  const hashes = {};
  for (const name of names) {
    hashes[`translate/${name}`] = sha256Hex(fs.readFileSync(path.join(builderDir, name)));
  }
  return hashes;
}

export function buildManifest(builderPath, plannedFiles, classifications) {
  requireNoGeneratedHandAuthoredCollision(plannedFiles, classifications);
  const files = {};
  for (const file of plannedFiles) files[file.path] = sha256Hex(file.content);
  const handAuthored = Object.keys(classifications)
    .filter((filePath) => classifications[filePath].startsWith("hand-authored"));
  const manifest = {
    builder: builderPath,
    builder_files: hashBuilderFiles(),
    files: sortedByKey(files),
    classes: sortedByKey(classifications),
    hand_authored: handAuthored,
  };
  const content = `${JSON.stringify(manifest, null, 2)}\n`;
  return { path: MANIFEST_PATH, content };
}
