// parse-sources.mjs: reads and validates the translator's inputs; every
// failure is a SourceError naming the file, so codex.mjs can exit 2 with it.
import fs from "node:fs";

export class SourceError extends Error {
  constructor(file, why) { super(`${file}: ${why}`); this.file = file; }
}

export function splitFrontmatter(text, file) {
  const match = /^---\n([\s\S]*?)\n---\n?/.exec(text);
  if (!match) throw new SourceError(file, "no frontmatter block");
  const fields = {};
  for (const line of match[1].split("\n")) {
    const kv = /^([A-Za-z-]+):\s*(.*)$/.exec(line);
    if (kv) fields[kv[1]] = kv[2];
  }
  if (!fields.name) throw new SourceError(file, "frontmatter has no name");
  return { frontmatter: fields, rawFrontmatter: match[1], body: text.slice(match[0].length) };
}

export function loadTextFile(file) {
  try { return fs.readFileSync(file, "utf8"); }
  catch { throw new SourceError(file, "missing or unreadable"); }
}

export function loadJsonFile(file) {
  let text;
  try { text = fs.readFileSync(file, "utf8"); }
  catch { throw new SourceError(file, "missing or unreadable"); }
  try { return JSON.parse(text); }
  catch (err) { throw new SourceError(file, `unparseable JSON (${err.message})`); }
}

export function loadSettingsHooks(file) {
  const settings = loadJsonFile(file);
  if (!settings.hooks) throw new SourceError(file, "no hooks object");
  return settings.hooks;
}

export function loadPortMap(file) {
  const map = loadJsonFile(file);
  for (const key of ["events", "unported_reasons", "agents_to_skills", "hand_authored"])
    if (!(key in map)) throw new SourceError(file, `port map missing ${key}`);
  if (!("port_status_appendix" in map)) map.port_status_appendix = "";
  return map;
}

// renderGeneratedHeader(source): the one GENERATED-header line every rendered
// codex/ file carries, naming the claude/ source it came from. Shared by
// every renderer so the wording only lives in one place.
export function renderGeneratedHeader(source) {
  return `<!-- GENERATED by translate/codex.mjs from ${source}. Do not edit; change the source and run: node translate/codex.mjs --write -->`;
}

// hookNameFromCommand(command): the hook name is the basename of the
// registered command's script without its .sh extension, e.g.
// "~/.claude/hooks/alpha-guard.sh" -> "alpha-guard". Exported: the
// hooks.json renderer (Task 6) needs the same name derivation as this file's
// own port checks.
export function hookNameFromCommand(command) {
  const base = command.split("/").pop();
  return base.endsWith(".sh") ? base.slice(0, -3) : base;
}

// hasUnportedReason(hookName, portMap): true when the port map's own
// unported_reasons object carries an entry for this hook. hasOwnProperty, not
// `in`: `in` walks the prototype chain, so a hook literally named "constructor"
// or "toString" read as carrying a reason it never had and dropped out of the
// generated Codex hooks (audit P3-1 fixed this in codex.mjs's closure check and
// left it standing here, reported on PR #8). Every classification path asks
// this one function so the two answers cannot diverge again.
export function hasUnportedReason(hookName, portMap) {
  return Object.prototype.hasOwnProperty.call(portMap.unported_reasons, hookName);
}

// isRegistrationPorted(hookName, event, portMap): true when this specific
// Claude Code event's registration of hookName would carry into Codex: the
// hook has no unported reason, and this event maps to a real Codex event.
// Registration-scoped, unlike isHookPorted's whole-hook "ported somewhere"
// answer, so a hook registered under both a ported and an unported event
// gets the right answer for each (the PORT-STATUS.md renderer, Task 6, needs
// one row per registration, not one row per hook).
export function isRegistrationPorted(hookName, event, portMap) {
  if (hasUnportedReason(hookName, portMap)) return false;
  return portMap.events[event] != null;
}

// isHookPorted(hookName, settingsHooks, portMap): a hook is ported when at
// least one of its settings.json registrations sits under an event whose
// port-map events entry is non-null, and the hook is not listed in
// portMap.unported_reasons. Source-agnostic: shared by the AGENTS.md tag
// rewriter (Task 5) and the hooks.json renderer (Task 6).
export function isHookPorted(hookName, settingsHooks, portMap) {
  for (const [event, groups] of Object.entries(settingsHooks)) {
    for (const group of groups) {
      for (const hook of group.hooks ?? []) {
        if (hookNameFromCommand(hook.command) === hookName && isRegistrationPorted(hookName, event, portMap)) return true;
      }
    }
  }
  return false;
}
